{% set name = "bundler" %}
{% set version = "2.2.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 65d7c3dc82651915d49a408769b6c5ccde8103b27a8b9be1c674899594613994

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win or ruby == '2.6' }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - bundle --help
    - bundler --help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Bundler manages an application's dependencies through its entire life, across many machines, systematically and repeatably

  doc_url: https://bundler.io/docs.html
  dev_url: https://github.com/bundler/{{ name }}

extra:
  recipe-maintainers:
    - sodre
