{% set name = "bundler" %}
{% set version = "2.2.3" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6acefda4aeb34cb3d69aff06affce10424d69f484402a9f7f5577e8c698070db

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win or ruby == '2.6' }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - bundle --help
    - bundler --help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Bundler manages an application's dependencies through its entire life, across many machines, systematically and repeatably

  doc_url: https://bundler.io/docs.html
  dev_url: https://github.com/bundler/{{ name }}

extra:
  recipe-maintainers:
    - sodre
