travis:
  secure:
    BINSTAR_TOKEN: MoRFNS10D6kOIT3V256qGV0gAWTLNXWhXRCYODeKYzbm0mdXI6F1EcHudA+wvj8YWT9RGHl25E3hUwLOvMUS7dcGRA9s0emYmA3DwmUdwllU4VeZv/IyFowN76vXgn0wu8spvtzWxG52q4yRTD1sNaDMcZKYSy9z1aCnWJajVcgsdTL+javL60zNhFHU9G/RMD1zvHrCkGZVKlIyyJfgCdiyu1Ef16n933xFofNdQ3gL29tSQokgnutW6FsRJML8P0YX+5J2YEg008O2Q0iJUPzkblAPC4OmTS+7mmnjaedYzxULdSIP92A++P/yAUk9DrDLGx4t85jVYB+rDZJkwR0EKzlL1g58n+NNE6RQNTx08tx7IqgxRy6+BawSCmMNYFvVh2WwY17lt+onDu+4c/7hmQxgeMU3yRdgrWtwnRqf+4o3uUROjC2dqEDp7CZ1As7+bcFjVxMOr6qW3q+B83I2doqeed8Lwlgnr1dxWYH54jyRxhdb5GWTXzZtyTsqTTuI36ivBsmtF9/GVErCmkakW2WcM7vMe19nZ3R09ZzrQeE4sJKCujBsISfQldmesxVmGqCs5SAEjYJmTxczfqP6yd+uV27mC8Fm6Ued8MlKvGbVMcsSPi/jOyoNL2KurOdJm5BaYlMZYBUy+vxX6209iCLVBk04il6QiZLJyps=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
